version: '3'
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=my_db
    volumes:
      - my-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  my-volume:
    external: true
